### ISSUE TITLE
Error starting image on Mac Silicon

### ISSUE THREAD

**Issue by ChristianAlfredsson** [helsingborg-stad/F-AI#63]
Have followed instructions. Docker image and build worked great.

Starting with this command: 
docker run \
   --name f-ai-pp-local \
   -e CHAINLIT_PORT=8001 \
   -p 8001:8001 \
   -v "$(pwd)"/src/planning_permission/.env:/app/.env \
   -v "$(pwd)"/src/planning_permission/data:/app/data \
   -v "$(pwd)"/src/planning_permission:/app/planning_permission \
   --platform linux/amd64 \
   f-ai-pp:local

Got this error:

2024-04-05 08:21:25 - Created default config file at /app/.chainlit/config.toml
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/venv/lib/python3.11/site-packages/chainlit/__main__.py", line 4, in <module>
    cli(prog_name="chainlit")
  File "/opt/venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/chainlit/cli/__init__.py", line 152, in chainlit_run
    run_chainlit(target)
  File "/opt/venv/lib/python3.11/site-packages/chainlit/cli/__init__.py", line 45, in run_chainlit
    load_module(config.run.module_name)
  File "/opt/venv/lib/python3.11/site-packages/chainlit/config.py", line 247, in load_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/planning_permission/app_main_stream.py", line 55, in <module>
    document_store.load_all_documents_in_path()
  File "/app/planning_permission/store/document_store.py", line 83, in load_all_documents_in_path
    all_dokuments_in_path = self.document_path + '*'
                            ~~~~~~~~~~~~~~~~~~~^~~~~
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'


Running on Macbook M1 Pro, latest Docker.

**Comment by zilaei** [comment]
Sorry @ChristianAlfredsson for the late answer!
Could you confirm if the problem still exist with the latest code in the main branch?
